project:
  type: website
  output-dir: docs

website:
  title: "Kelvin K Portfolio"
  sidebar:
    style: "docked"
    search: false
    contents: 
      - href: index.qmd
        text: Home
      - PointEstimation.qmd
      - lab 2/Lab2WriteUp.qmd
      - lab 3/Lab3WriteUp.qmd
      - lab 4/Lab4WriteUp.qmd
      - lab 5&6/Lab5WriteUp.qmd
      - lab 8&9/Lab8WriteUp.qmd
      - lab 10/Lab10WriteUp.qmd
      - lab 11/Lab11WriteUp.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


